apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: kevinstudy0829/docker-fastapi:4540c3ee3dbc8cca1e2ca614a4b03de32d8a86af
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: fastapi-config
            - secretRef:
                name: fastapi-secret
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
